UIObject = {
	inherits = {
		"UIObject",
	},
	methods = {
		"GetDebugName",
		"GetName",
		"GetObjectType",
		"IsForbidden",
		"IsObjectType",
	},
}

ParentedObject = {
	inherits = {
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"GetDebugName",
		"GetName",
		"GetObjectType",
		"GetParent",
		"IsForbidden",
		"IsObjectType",
	},
}

ScriptObject = {
	inherits = {
		"ScriptObject",
	},
	methods = {
		"GetScript",
		"HasScript",
		"HookScript",
		"SetScript",
	},
}

Region = {
	inherits = {
		"Region",
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"CanChangeProtectedState",
		"ClearAllPoints",
		"GetBottom",
		"GetCenter",
		"GetDebugName",
		"GetHeight",
		"GetLeft",
		"GetName",
		"GetNumPoints",
		"GetObjectType",
		"GetParent",
		"GetPoint",
		"GetRect",
		"GetRight",
		"GetSize",
		"GetTop",
		"GetWidth",
		"IsDragging",
		"IsForbidden",
		"IsMouseOver",
		"IsObjectType",
		"IsProtected",
		"SetAllPoints",
		"SetHeight",
		"SetParent",
		"SetPoint",
		"SetSize",
		"SetWidth",
	},
}

VisibleRegion = {
	inherits = {
		"VisibleRegion",
		"Region",
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"CanChangeProtectedState",
		"ClearAllPoints",
		"GetAlpha",
		"GetBottom",
		"GetCenter",
		"GetDebugName",
		"GetHeight",
		"GetLeft",
		"GetName",
		"GetNumPoints",
		"GetObjectType",
		"GetParent",
		"GetPoint",
		"GetRect",
		"GetRight",
		"GetSize",
		"GetTop",
		"GetWidth",
		"Hide",
		"IsDragging",
		"IsForbidden",
		"IsMouseOver",
		"IsObjectType",
		"IsProtected",
		"IsShown",
		"IsVisible",
		"SetAllPoints",
		"SetAlpha",
		"SetHeight",
		"SetParent",
		"SetPoint",
		"SetSize",
		"SetWidth",
		"Show",
	},
}

AnimationGroup = {
	inherits = {
		"AnimationGroup",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnLoop"] = "self, loopState",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"CreateAnimation",
		"Finish",
		"GetAnimations",
		"GetDebugName",
		"GetDuration",
		"GetLooping",
		"GetLoopState",
		"GetName",
		"GetObjectType",
		"GetProgress",
		"GetScript",
		"HasScript",
		"HookScript",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPendingFinish",
		"IsPlaying",
		"IsSetToFinalAlpha",
		"Pause",
		"Play",
		"Restart",
		"SetLooping",
		"SetScript",
		"SetToFinalAlpha",
		"Stop",
	},
}

Animation = {
	inherits = {
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDuration",
		"SetEndDelay",
		"SetOrder",
		"SetParent",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"Stop",
	},
}

Alpha = {
	inherits = {
		"Alpha",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetFromAlpha",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"GetToAlpha",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDuration",
		"SetEndDelay",
		"SetFromAlpha",
		"SetOrder",
		"SetParent",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"SetToAlpha",
		"Stop",
	},
}

Path = {
	inherits = {
		"Path",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"CreateControlPoint",
		"GetControlPoints",
		"GetCurve",
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetMaxOrder",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetCurve",
		"SetDuration",
		"SetEndDelay",
		"SetOrder",
		"SetParent",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"Stop",
	},
}

Rotation = {
	inherits = {
		"Rotation",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDegrees",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetOrigin",
		"GetParent",
		"GetProgress",
		"GetRadians",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDegrees",
		"SetDuration",
		"SetEndDelay",
		"SetOrder",
		"SetOrigin",
		"SetParent",
		"SetRadians",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"Stop",
	},
}

Scale = {
	inherits = {
		"Scale",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetFromScale",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetOrigin",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScale",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"GetToScale",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDuration",
		"SetEndDelay",
		"SetFromScale",
		"SetOrder",
		"SetOrigin",
		"SetParent",
		"SetScale",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"SetToScale",
		"Stop",
	},
}

LineScale = {
	inherits = {
		"LineScale",
		"Scale",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDuration",
		"SetEndDelay",
		"SetOrder",
		"SetParent",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"Stop",
	},
}

TextureCoordTranslation = {
	inherits = {
		"TextureCoordTranslation",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetName",
		"GetObjectType",
		"GetOffset",
		"GetOrder",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDuration",
		"SetEndDelay",
		"SetOffset",
		"SetOrder",
		"SetParent",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"Stop",
	},
}

Translation = {
	inherits = {
		"Translation",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetName",
		"GetObjectType",
		"GetOffset",
		"GetOrder",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDuration",
		"SetEndDelay",
		"SetOffset",
		"SetOrder",
		"SetParent",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"Stop",
	},
}

ControlPoint = {
	inherits = {
		"ControlPoint",
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"GetDebugName",
		"GetName",
		"GetObjectType",
		"GetOffset",
		"GetOrder",
		"GetParent",
		"IsForbidden",
		"IsObjectType",
		"SetOffset",
		"SetOrder",
		"SetParent",
	},
}