UIObject = {
	inherits = {
		"UIObject",
	},
	methods = {
		"GetDebugName",
		"GetName",
		"GetObjectType",
		"IsForbidden",
		"IsObjectType",
	},
}

ParentedObject = {
	inherits = {
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"GetDebugName",
		"GetName",
		"GetObjectType",
		"GetParent",
		"IsForbidden",
		"IsObjectType",
	},
}

ScriptObject = {
	inherits = {
		"ScriptObject",
	},
	methods = {
		"GetScript",
		"HasScript",
		"HookScript",
		"SetScript",
	},
}

Region = {
	inherits = {
		"Region",
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"CanChangeProtectedState",
		"ClearAllPoints",
		"CreateAnimationGroup",
		"GetAnimationGroups",
		"GetBottom",
		"GetCenter",
		"GetDebugName",
		"GetHeight",
		"GetLeft",
		"GetName",
		"GetNumPoints",
		"GetObjectType",
		"GetParent",
		"GetPoint",
		"GetRect",
		"GetRight",
		"GetSize",
		"GetTop",
		"GetWidth",
		"IsDragging",
		"IsForbidden",
		"IsMouseOver",
		"IsObjectType",
		"IsProtected",
		"SetAllPoints",
		"SetHeight",
		"SetParent",
		"SetPoint",
		"SetSize",
		"SetWidth",
		"StopAnimating",
	},
}

VisibleRegion = {
	inherits = {
		"VisibleRegion",
		"Region",
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"CanChangeProtectedState",
		"ClearAllPoints",
		"CreateAnimationGroup",
		"GetAlpha",
		"GetAnimationGroups",
		"GetBottom",
		"GetCenter",
		"GetDebugName",
		"GetHeight",
		"GetLeft",
		"GetName",
		"GetNumPoints",
		"GetObjectType",
		"GetParent",
		"GetPoint",
		"GetRect",
		"GetRight",
		"GetSize",
		"GetTop",
		"GetWidth",
		"Hide",
		"IsDragging",
		"IsForbidden",
		"IsMouseOver",
		"IsObjectType",
		"IsProtected",
		"IsShown",
		"IsVisible",
		"SetAllPoints",
		"SetAlpha",
		"SetHeight",
		"SetParent",
		"SetPoint",
		"SetSize",
		"SetWidth",
		"Show",
		"StopAnimating",
	},
}

LayeredRegion = {
	inherits = {
		"LayeredRegion",
		"VisibleRegion",
		"Region",
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"CanChangeProtectedState",
		"ClearAllPoints",
		"CreateAnimationGroup",
		"GetAlpha",
		"GetAnimationGroups",
		"GetBottom",
		"GetCenter",
		"GetDebugName",
		"GetDrawLayer",
		"GetHeight",
		"GetLeft",
		"GetName",
		"GetNumPoints",
		"GetObjectType",
		"GetParent",
		"GetPoint",
		"GetRect",
		"GetRight",
		"GetSize",
		"GetTop",
		"GetWidth",
		"Hide",
		"IsDragging",
		"IsForbidden",
		"IsMouseOver",
		"IsObjectType",
		"IsProtected",
		"IsShown",
		"IsVisible",
		"SetAllPoints",
		"SetAlpha",
		"SetDrawLayer",
		"SetHeight",
		"SetParent",
		"SetPoint",
		"SetSize",
		"SetVertexColor",
		"SetWidth",
		"Show",
		"StopAnimating",
	},
}

AnimationGroup = {
	inherits = {
		"AnimationGroup",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnLoop"] = "self, loopState",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"CreateAnimation",
		"Finish",
		"GetAnimations",
		"GetDebugName",
		"GetDuration",
		"GetLooping",
		"GetLoopState",
		"GetName",
		"GetObjectType",
		"GetParent",
		"GetProgress",
		"GetScript",
		"HasScript",
		"HookScript",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPendingFinish",
		"IsPlaying",
		"IsSetToFinalAlpha",
		"Pause",
		"Play",
		"Restart",
		"SetLooping",
		"SetScript",
		"SetToFinalAlpha",
		"Stop",
	},
}

Animation = {
	inherits = {
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDuration",
		"SetEndDelay",
		"SetOrder",
		"SetParent",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"Stop",
	},
}

Alpha = {
	inherits = {
		"Alpha",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetFromAlpha",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"GetToAlpha",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDuration",
		"SetEndDelay",
		"SetFromAlpha",
		"SetOrder",
		"SetParent",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"SetToAlpha",
		"Stop",
	},
}

Path = {
	inherits = {
		"Path",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"CreateControlPoint",
		"GetControlPoints",
		"GetCurve",
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetMaxOrder",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetCurve",
		"SetDuration",
		"SetEndDelay",
		"SetOrder",
		"SetParent",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"Stop",
	},
}

Rotation = {
	inherits = {
		"Rotation",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDegrees",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetOrigin",
		"GetParent",
		"GetProgress",
		"GetRadians",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDegrees",
		"SetDuration",
		"SetEndDelay",
		"SetOrder",
		"SetOrigin",
		"SetParent",
		"SetRadians",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"Stop",
	},
}

Scale = {
	inherits = {
		"Scale",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetFromScale",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetOrigin",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScale",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"GetToScale",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDuration",
		"SetEndDelay",
		"SetFromScale",
		"SetOrder",
		"SetOrigin",
		"SetParent",
		"SetScale",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"SetToScale",
		"Stop",
	},
}

LineScale = {
	inherits = {
		"LineScale",
		"Scale",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetFromScale",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetOrigin",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScale",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"GetToScale",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDuration",
		"SetEndDelay",
		"SetFromScale",
		"SetOrder",
		"SetOrigin",
		"SetParent",
		"SetScale",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"SetToScale",
		"Stop",
	},
}

TextureCoordTranslation = {
	inherits = {
		"TextureCoordTranslation",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetName",
		"GetObjectType",
		"GetOrder",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDuration",
		"SetEndDelay",
		"SetOrder",
		"SetParent",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"Stop",
	},
}

Translation = {
	inherits = {
		"Translation",
		"Animation",
		"ScriptObject",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnFinished"] = "self, requested",
		["OnLoad"] = "self",
		["OnPause"] = "self",
		["OnPlay"] = "self",
		["OnStop"] = "self, requested",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"GetDebugName",
		"GetDuration",
		"GetElapsed",
		"GetEndDelay",
		"GetName",
		"GetObjectType",
		"GetOffset",
		"GetOrder",
		"GetParent",
		"GetProgress",
		"GetRegionParent",
		"GetScript",
		"GetSmoothing",
		"GetSmoothProgress",
		"GetStartDelay",
		"GetTarget",
		"HasScript",
		"HookScript",
		"IsDelaying",
		"IsDone",
		"IsForbidden",
		"IsObjectType",
		"IsPaused",
		"IsPlaying",
		"IsStopped",
		"Pause",
		"Play",
		"Restart",
		"SetChildKey",
		"SetDuration",
		"SetEndDelay",
		"SetOffset",
		"SetOrder",
		"SetParent",
		"SetScript",
		"SetSmoothing",
		"SetSmoothProgress",
		"SetStartDelay",
		"SetTarget",
		"SetTargetKey",
		"Stop",
	},
}

ControlPoint = {
	inherits = {
		"ControlPoint",
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"GetDebugName",
		"GetName",
		"GetObjectType",
		"GetOffset",
		"GetOrder",
		"GetParent",
		"IsForbidden",
		"IsObjectType",
		"SetOffset",
		"SetOrder",
		"SetParent",
	},
}

FontInstance = {
	inherits = {
		"FontInstance",
		"UIObject",
	},
	methods = {
		"GetDebugName",
		"GetFont",
		"GetFontObject",
		"GetJustifyH",
		"GetJustifyV",
		"GetName",
		"GetObjectType",
		"GetShadowColor",
		"GetShadowOffset",
		"GetSpacing",
		"GetTextColor",
		"IsForbidden",
		"IsObjectType",
		"SetFont",
		"SetFontObject",
		"SetJustifyH",
		"SetJustifyV",
		"SetShadowColor",
		"SetShadowOffset",
		"SetSpacing",
		"SetTextColor",
	},
}

Font = {
	inherits = {
		"Font",
		"FontInstance",
		"UIObject",
	},
	methods = {
		"CopyFontObject",
		"GetAlpha",
		"GetFont",
		"GetFontObject",
		"GetIndentedWordWrap",
		"GetJustifyH",
		"GetJustifyV",
		"GetName",
		"GetObjectType",
		"GetShadowColor",
		"GetShadowOffset",
		"GetSpacing",
		"GetTextColor",
		"IsObjectType",
		"SetAlpha",
		"SetFont",
		"SetFontObject",
		"SetIndentedWordWrap",
		"SetJustifyH",
		"SetJustifyV",
		"SetShadowColor",
		"SetShadowOffset",
		"SetSpacing",
		"SetTextColor",
	},
}

FontString = {
	inherits = {
		"FontString",
		"FontInstance",
		"LayeredRegion",
		"VisibleRegion",
		"Region",
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"CanChangeProtectedState",
		"CanNonSpaceWrap",
		"CanWordWrap",
		"ClearAllPoints",
		"CreateAnimationGroup",
		"GetAlpha",
		"GetAnimationGroups",
		"GetBottom",
		"GetCenter",
		"GetDebugName",
		"GetDrawLayer",
		"GetFieldSize",
		"GetFont",
		"GetFontObject",
		"GetHeight",
		"GetIndentedWordWrap",
		"GetJustifyH",
		"GetJustifyV",
		"GetLeft",
		"GetLineHeight",
		"GetMaxLines",
		"GetName",
		"GetNumLines",
		"GetNumPoints",
		"GetObjectType",
		"GetParent",
		"GetPoint",
		"GetRect",
		"GetRight",
		"GetShadowColor",
		"GetShadowOffset",
		"GetSize",
		"GetSpacing",
		"GetStringHeight",
		"GetStringWidth",
		"GetText",
		"GetTextColor",
		"GetTop",
		"GetWidth",
		"GetWrappedWidth",
		"Hide",
		"IsDragging",
		"IsForbidden",
		"IsIgnoringParentAlpha",
		"IsIgnoringParentScale",
		"IsMouseOver",
		"IsObjectLoaded",
		"IsObjectType",
		"IsProtected",
		"IsShown",
		"IsTruncated",
		"IsVisible",
		"SetAllPoints",
		"SetAlpha",
		"SetAlphaGradient",
		"SetDrawLayer",
		"SetFont",
		"SetFontObject",
		"SetFormattedText",
		"SetHeight",
		"SetIgnoreParentAlpha",
		"SetIgnoreParentScale",
		"SetIndentedWordWrap",
		"SetJustifyH",
		"SetJustifyV",
		"SetMaxLines",
		"SetNonSpaceWrap",
		"SetParent",
		"SetPoint",
		"SetShadowColor",
		"SetShadowOffset",
		"SetShown",
		"SetSize",
		"SetSpacing",
		"SetText",
		"SetTextColor",
		"SetTextHeight",
		"SetVertexColor",
		"SetWidth",
		"SetWordWrap",
		"Show",
		"StopAnimating",
	},
}

Texture = {
	inherits = {
		"Texture",
		"LayeredRegion",
		"VisibleRegion",
		"Region",
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"AddMaskTexture",
		"CanChangeProtectedState",
		"ClearAllPoints",
		"CreateAnimationGroup",
		"GetAlpha",
		"GetAnimationGroups",
		"GetAtlas",
		"GetBlendMode",
		"GetBottom",
		"GetCenter",
		"GetDebugName",
		"GetDesaturation",
		"GetDrawLayer",
		"GetHeight",
		"GetHorizTile",
		"GetLeft",
		"GetName",
		"GetNonBlocking",
		"GetNumPoints",
		"GetObjectType",
		"GetParent",
		"GetPoint",
		"GetRect",
		"GetRight",
		"GetSize",
		"GetTexCoord",
		"GetTexture",
		"GetTop",
		"GetVertexColor",
		"GetVertexOffset",
		"GetVertTile",
		"GetWidth",
		"Hide",
		"IsDesaturated",
		"IsDragging",
		"IsForbidden",
		"IsIgnoringParentAlpha",
		"IsIgnoringParentScale",
		"IsMouseOver",
		"IsObjectLoaded",
		"IsObjectType",
		"IsProtected",
		"IsShown",
		"IsVisible",
		"RemoveMaskTexture",
		"SetAllPoints",
		"SetAlpha",
		"SetAtlas",
		"SetBlendMode",
		"SetColorTexture",
		"SetDesaturated",
		"SetDesaturation",
		"SetDrawLayer",
		"SetGradient",
		"SetGradientAlpha",
		"SetHeight",
		"SetHorizTile",
		"SetIgnoreParentAlpha",
		"SetIgnoreParentScale",
		"SetMask",
		"SetNonBlocking",
		"SetParent",
		"SetPoint",
		"SetRotation",
		"SetShown",
		"SetSize",
		"SetTexCoord",
		"SetTexture",
		"SetVertexColor",
		"SetVertexOffset",
		"SetVertTile",
		"SetWidth",
		"Show",
		"StopAnimating",
	},
}

Line = {
	inherits = {
		"Line",
		"Texture",
		"LayeredRegion",
		"VisibleRegion",
		"Region",
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"CanChangeProtectedState",
		"CreateAnimationGroup",
		"GetAlpha",
		"GetAnimationGroups",
		"GetAtlas",
		"GetBlendMode",
		"GetBottom",
		"GetCenter",
		"GetDebugName",
		"GetDesaturation",
		"GetDrawLayer",
		"GetEndPoint",
		"GetHeight",
		"GetHorizTile",
		"GetLeft",
		"GetName",
		"GetNonBlocking",
		"GetObjectType",
		"GetParent",
		"GetRect",
		"GetRight",
		"GetSize",
		"GetStartPoint",
		"GetTexCoord",
		"GetTexture",
		"GetThickness",
		"GetTop",
		"GetVertexColor",
		"GetVertexOffset",
		"GetVertTile",
		"GetWidth",
		"Hide",
		"IsDesaturated",
		"IsDragging",
		"IsForbidden",
		"IsIgnoringParentAlpha",
		"IsIgnoringParentScale",
		"IsMouseOver",
		"IsObjectLoaded",
		"IsObjectType",
		"IsProtected",
		"IsShown",
		"IsVisible",
		"SetAlpha",
		"SetAtlas",
		"SetBlendMode",
		"SetColorTexture",
		"SetDesaturated",
		"SetDesaturation",
		"SetDrawLayer",
		"SetEndPoint",
		"SetGradient",
		"SetGradientAlpha",
		"SetHorizTile",
		"SetIgnoreParentAlpha",
		"SetIgnoreParentScale",
		"SetMask",
		"SetNonBlocking",
		"SetParent",
		"SetRotation",
		"SetShown",
		"SetStartPoint",
		"SetTexCoord",
		"SetTexture",
		"SetThickness",
		"SetVertexColor",
		"SetVertexOffset",
		"SetVertTile",
		"Show",
		"StopAnimating",
	},
}

MaskTexture = {
	inherits = {
		"MaskTexture",
		"Texture",
		"LayeredRegion",
		"VisibleRegion",
		"Region",
		"ParentedObject",
		"UIObject",
	},
	methods = {
		"CanChangeProtectedState",
		"ClearAllPoints",
		"CreateAnimationGroup",
		"GetAlpha",
		"GetAnimationGroups",
		"GetAtlas",
		"GetBlendMode",
		"GetBottom",
		"GetCenter",
		"GetDebugName",
		"GetDesaturation",
		"GetDrawLayer",
		"GetHeight",
		"GetHorizTile",
		"GetLeft",
		"GetName",
		"GetNonBlocking",
		"GetNumPoints",
		"GetObjectType",
		"GetParent",
		"GetPoint",
		"GetRect",
		"GetRight",
		"GetSize",
		"GetTexCoord",
		"GetTexture",
		"GetTop",
		"GetVertexColor",
		"GetVertexOffset",
		"GetVertTile",
		"GetWidth",
		"Hide",
		"IsDesaturated",
		"IsDragging",
		"IsForbidden",
		"IsIgnoringParentAlpha",
		"IsIgnoringParentScale",
		"IsMouseOver",
		"IsObjectLoaded",
		"IsObjectType",
		"IsProtected",
		"IsShown",
		"IsVisible",
		"SetAllPoints",
		"SetAlpha",
		"SetAtlas",
		"SetBlendMode",
		"SetColorTexture",
		"SetDesaturated",
		"SetDesaturation",
		"SetDrawLayer",
		"SetGradient",
		"SetGradientAlpha",
		"SetHeight",
		"SetHorizTile",
		"SetIgnoreParentAlpha",
		"SetIgnoreParentScale",
		"SetMask",
		"SetNonBlocking",
		"SetParent",
		"SetPoint",
		"SetRotation",
		"SetShown",
		"SetSize",
		"SetTexCoord",
		"SetTexture",
		"SetVertexColor",
		"SetVertexOffset",
		"SetVertTile",
		"SetWidth",
		"Show",
		"StopAnimating",
	},
}

Frame = {
	inherits = {
		"Frame",
		"ScriptObject",
		"VisibleRegion",
		"Region",
		"ParentedObject",
		"UIObject",
	},
	handlers = {
		["OnAttributeChanged"] = "self, name, value",
		["OnChar"] = "self, text",
		["OnDisable"] = "self",
		["OnDragStart"] = "self, button",
		["OnDragStop"] = "self",
		["OnEnable"] = "self",
		["OnEnter"] = "self, motion",
		["OnEvent"] = "self, event, ...",
		["OnHide"] = "self",
		["OnHyperlinkClick"] = "self, link, text, button, region, left, bottom, width, height",
		["OnHyperlinkEnter"] = "self, link, text, region, left, bottom, width, height",
		["OnHyperlinkLeave"] = "self",
		["OnKeyDown"] = "self, key",
		["OnKeyUp"] = "self, key",
		["OnLeave"] = "self, motion",
		["OnLoad"] = "self",
		["OnMouseDown"] = "self, button",
		["OnMouseUp"] = "self, button, upInside",
		["OnMouseWheel"] = "self, delta",
		["OnReceiveDrag"] = "self",
		["OnShow"] = "self",
		["OnSizeChanged"] = "self, w, h",
		["OnUpdate"] = "self, elapsed",
	},
	methods = {
		"CanChangeAttribute",
		"CanChangeProtectedState",
		"ClearAllPoints",
		"CreateAnimationGroup",
		"CreateFontString",
		"CreateLine",
		"CreateMaskTexture",
		"CreateTexture",
		"DisableDrawLayer",
		"DoesClipChildren",
		"EnableDrawLayer",
		"EnableJoystick",
		"EnableKeyboard",
		"EnableMouse",
		"EnableMouseWheel",
		"GetAlpha",
		"GetAnimationGroups",
		"GetAttribute",
		"GetBackdrop",
		"GetBackdropBorderColor",
		"GetBackdropColor",
		"GetBottom",
		"GetBoundsRect",
		"GetCenter",
		"GetChildren",
		"GetClampRectInsets",
		"GetDebugName",
		"GetDepth",
		"GetDontSavePosition",
		"GetEffectiveAlpha",
		"GetEffectiveDepth",
		"GetEffectivelyFlattensRenderLayers",
		"GetEffectiveScale",
		"GetFlattensRenderLayers",
		"GetFrameLevel",
		"GetFrameStrata",
		"GetHeight",
		"GetHitRectInsets",
		"GetHyperlinksEnabled",
		"GetID",
		"GetLeft",
		"GetMaxResize",
		"GetMinResize",
		"GetName",
		"GetNumChildren",
		"GetNumPoints",
		"GetNumRegions",
		"GetObjectType",
		"GetParent",
		"GetPoint",
		"GetPropagateKeyboardInput",
		"GetRect",
		"GetRegions",
		"GetRight",
		"GetScale",
		"GetScript",
		"GetSize",
		"GetTop",
		"GetWidth",
		"HasScript",
		"Hide",
		"HookScript",
		"IgnoreDepth",
		"IsClampedToScreen",
		"IsDragging",
		"IsEventRegistered",
		"IsForbidden",
		"IsIgnoringDepth",
		"IsIgnoringParentAlpha",
		"IsIgnoringParentScale",
		"IsJoystickEnabled",
		"IsKeyboardEnabled",
		"IsMouseClickEnabled",
		"IsMouseEnabled",
		"IsMouseMotionEnabled",
		"IsMouseOver",
		"IsMouseWheelEnabled",
		"IsMovable",
		"IsObjectLoaded",
		"IsObjectType",
		"IsProtected",
		"IsResizable",
		"IsShown",
		"IsToplevel",
		"IsUserPlaced",
		"IsVisible",
		"Lower",
		"Raise",
		"RegisterAllEvents",
		"RegisterEvent",
		"RegisterForDrag",
		"RegisterUnitEvent",
		"SetAllPoints",
		"SetAlpha",
		"SetAttribute",
		"SetBackdrop",
		"SetBackdropBorderColor",
		"SetBackdropColor",
		"SetClampedToScreen",
		"SetClampRectInsets",
		"SetClipsChildren",
		"SetDepth",
		"SetDontSavePosition",
		"SetFlattensRenderLayers",
		"SetFrameLevel",
		"SetFrameStrata",
		"SetHeight",
		"SetHitRectInsets",
		"SetHyperlinksEnabled",
		"SetID",
		"SetIgnoreParentAlpha",
		"SetIgnoreParentScale",
		"SetMaxResize",
		"SetMinResize",
		"SetMouseClickEnabled",
		"SetMouseMotionEnabled",
		"SetMovable",
		"SetParent",
		"SetPoint",
		"SetPropagateKeyboardInput",
		"SetResizable",
		"SetScale",
		"SetScript",
		"SetShown",
		"SetSize",
		"SetToplevel",
		"SetUserPlaced",
		"SetWidth",
		"Show",
		"StartMoving",
		"StartSizing",
		"StopAnimating",
		"StopMovingOrSizing",
		"UnregisterAllEvents",
		"UnregisterEvent",
	},
}